seed: 42
dataset:
  name: under
  load_data: true
  test_split_size: 0.2
  val_split_size: 0.2
  resample: true
model:
  name: ccnn3
  bias: true
  loss: BCELoss
  dropout: 0.35
  num_blocks: 2
  hidden_channels: 32
training:
  lr: 1.0e-05
  batch_size: 64
  weight_decay: 1.0e-05
  patience: 10
  optim: RAdam
  metrics: f1-score
  epochs: 30
kernel:
  activation: Sine
  hidden_channels: 32
  dropout: 0.3
  norm_type: boh
  omega_0: 56
  bias: true
  conv_use_fft: false
