torch:
  device: cpu
  seed: 42

dataset:
  name: overunder
  train_size: 0.75
  test_size: 0.25
  val_size: 0.1
  batch_size: 64
  load_data: True
  resample: True
  scale: False

trainer:
  epochs: 30
  patience: 5
  lr: 0.000001
  weight_decay: 0.000001
  optim: RAdam
  metrics: Precision

whistlenet:
  name: ccnn3
  loss: BCELoss
  dropout: 0.3
  bias: True
  num_blocks: 4
  hidden_channels: 16
  kernel:
    type: KernelNet
    activation: ReLU
    linear_type: Linear1d
    norm_type: boh
    hidden_channels: 32
    dropout: 0.2
    omega_0: 750.0
    bias: True
    conv_use_fft: True

baseline:
  name: naodevils
  loss: BCELoss
  hidden_dropout: 0.3
  dropout: 0.3
  bias: True