torch:
  device: cpu
  seed: 42

dataset:
  name: naodevils
  train_size: 0.75
  test_size: 0.15
  val_size: 0.1
  batch_size: 128
  load_data: True
  resample: False

trainer:
  epochs: 30
  patience: 5
  lr: 0.0001
  weight_decay: 0.00001
  optim: RAdam
  metrics: F1Score
  batch_size: 128

whistlenet:
  name: ccnn1
  loss: BCELoss
  in_channels: 1
  out_channels: 1
  dropout: 0.2
  bias: True
  num_blocks: 2
  hidden_channels: 32
  kernel:
    activation: Sine
    linear_type: Linear1d
    norm_type: boh
    hidden_channels: 32
    dropout: 0.2
    omega_0: 89
    bias: True
    conv_use_fft: True

baseline:
  name: cnn
  loss: BCELoss
  dropout: 0.2
  bias: True