seed: 3

# function stuff
function: Constant
min: -10
max : 10
samples: 201
gauss_sigma: 1
gauss_mean: 0

# model stuff
activation: Sine
linear_type: Linear1d
bias: True
hidden_channels: 32
n_layers: 3
weight_dropout: 0.5
omega_0: 50

# training stuff
iterations: 1500
lr: 0.001
optim: Adam
