seed: 42

dataset:
  name: combined
  load_data: True
  test_split_size: 0.2
  val_split_size: 0.2
  resample: True

model:
  name: ccnn2
  bias: True
  loss: BCELoss
  dropout: 0.25
  num_blocks: 2
  hidden_channels: 2

training:
  lr: 0.0001
  batch_size: 64
  weight_decay: 0.001
  patience: 10
  optim: RAdam
  metrics: f1-score
  epochs: 30

kernel:
  activation: Sine
  hidden_channels: 20
  num_layers: 32
  dropout: 0.5
  norm_type: boh
  omega_0: 30
  bias: True