seed: 42

dataset:
  name: under
  load_data: False
  test_split_size: 0.2
  val_split_size: 0.2
  resample: False

model:
  name: ccnn6
  bias: True
  loss: BCELoss
  dropout: 0.2
  num_blocks: 1
  hidden_channels: 32

training:
  lr: 0.00001
  batch_size: 128
  weight_decay: 0.00001
  patience: 15
  optim: RAdam
  metrics: f1-score
  epochs: 30

kernel:
  activation: Sine
  hidden_channels: 32
  dropout: 0.3
  norm_type: boh
  omega_0: 69
  bias: True
  conv_use_fft: False