name: ccnn1
loss: BCELoss
in_channels: 1
out_channels: 1
bias: true
dropout: 0.2
num_blocks: 2
hidden_channels: 32
kernel:
  activation: Sine
  linear_type: Linear1d
  hidden_channels: 32
  dropout: 0.2
  norm_type: boh
  omega_0: 89.0
  bias: true
  conv_use_fft: true
